Feat/seo alt sup
Mydemenageur-Org/Mydemenageur-Site pull request #60
Opened 2022-01-21 14:44 UTC by LeoDELPON

SEO Optimization :
- Schema data structure for reviews (Redux, redux-saga), 
- Schema data structure for global review (Redux, redux-saga),
- Schema data structure for BreadCrumb,
- Schema data structure for Addresses,
- Binding internal mesh with review's page,
- Binding All alt props for images,
- Refactoring infrastructure with Hn system,
- Binding internal mesh in provider detail page,
- Refactoring the page for annuaire, annonce and votes for having multiple pages,
- Restructuring the Head component for dynamic schema,

2022-01-21 17:03 UTC, Tsekko requested changes

2022-01-21 17:03 UTC, Tsekko commented on pages/[helpService]/annonce/[searchType]/page/index/[annoncePage].tsx
> +        <link rel="icon" href="/favicon.ico" />
Missing canonical link

2022-01-21 17:03 UTC, Tsekko commented on pages/[helpService]/annonce/[searchType]/index.tsx
> +      <MDHead description="Annonces de services">
Missing canonical link

2022-01-21 17:03 UTC, Tsekko commented on pages/[helpService]/annuaire/[serviceProvider]/[locationId]/[profilId].tsx
> +        <title>MyDemenageur - Profil de {props.name}</title>
Missing canonical link

2022-01-23 12:13 UTC, LeoDELPON commented on pages/profil/password.tsx
> +<<<<<<< HEAD
Deleted HEAD token

2022-01-23 12:50 UTC, merged